### ISSUE TITLE
影片心得回覆

### ISSUE THREAD

**Issue by azole** [layla4131/hello-git#1]
謝謝你的總結，的確，很多人有偶像包袱後，反而就無法進步了，在資訊領域又特別明顯，畢竟新技術出來的很快、有太多東西需要學習...  我自己經常用這部影片來提醒我自己，希望這部影片也對你有用，接下來的課程，鼓勵你上課多積極參與，用成長型的思維、不怕犯錯的態度，來一起學習 NodeJS！

**Comment by layla4131** [comment]
謝謝老師~
